version: '2'

services:
  shortener-service:
    extends:
      file: common.yml
      service: shortener-service
    depends_on:
      - cassandra

  shortener-frontend:
    extends:
      file: common.yml
      service: shortener-frontend
    depends_on:
      - shortener-service

  cassandra:
    extends:
      file: common.yml
      service: cassandra
